apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: votingapp
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  project: default
  source:
    repoURL:
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Updates
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  project: default
  source:
    repoURL:
    targetVersion: HEAD
    path: votigapp
  destination:
    server: https://kubernetes.default.svc
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ArgoApps
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  project: default
  source:
    repoURL:
    targetRevision: HEAD
    path: ArgoApps
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
